require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LandsController do

  # This should return the minimal set of attributes required to create a valid
  # Land. As you add validations to Land, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lands as @lands" do
      land = Land.create! valid_attributes
      get :index
      assigns(:lands).should eq([land])
    end
  end

  describe "GET show" do
    it "assigns the requested land as @land" do
      land = Land.create! valid_attributes
      get :show, :id => land.id.to_s
      assigns(:land).should eq(land)
    end
  end

  describe "GET new" do
    it "assigns a new land as @land" do
      get :new
      assigns(:land).should be_a_new(Land)
    end
  end

  describe "GET edit" do
    it "assigns the requested land as @land" do
      land = Land.create! valid_attributes
      get :edit, :id => land.id.to_s
      assigns(:land).should eq(land)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Land" do
        expect {
          post :create, :land => valid_attributes
        }.to change(Land, :count).by(1)
      end

      it "assigns a newly created land as @land" do
        post :create, :land => valid_attributes
        assigns(:land).should be_a(Land)
        assigns(:land).should be_persisted
      end

      it "redirects to the created land" do
        post :create, :land => valid_attributes
        response.should redirect_to(Land.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved land as @land" do
        # Trigger the behavior that occurs when invalid params are submitted
        Land.any_instance.stub(:save).and_return(false)
        post :create, :land => {}
        assigns(:land).should be_a_new(Land)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Land.any_instance.stub(:save).and_return(false)
        post :create, :land => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested land" do
        land = Land.create! valid_attributes
        # Assuming there are no other lands in the database, this
        # specifies that the Land created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Land.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => land.id, :land => {'these' => 'params'}
      end

      it "assigns the requested land as @land" do
        land = Land.create! valid_attributes
        put :update, :id => land.id, :land => valid_attributes
        assigns(:land).should eq(land)
      end

      it "redirects to the land" do
        land = Land.create! valid_attributes
        put :update, :id => land.id, :land => valid_attributes
        response.should redirect_to(land)
      end
    end

    describe "with invalid params" do
      it "assigns the land as @land" do
        land = Land.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Land.any_instance.stub(:save).and_return(false)
        put :update, :id => land.id.to_s, :land => {}
        assigns(:land).should eq(land)
      end

      it "re-renders the 'edit' template" do
        land = Land.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Land.any_instance.stub(:save).and_return(false)
        put :update, :id => land.id.to_s, :land => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested land" do
      land = Land.create! valid_attributes
      expect {
        delete :destroy, :id => land.id.to_s
      }.to change(Land, :count).by(-1)
    end

    it "redirects to the lands list" do
      land = Land.create! valid_attributes
      delete :destroy, :id => land.id.to_s
      response.should redirect_to(lands_url)
    end
  end

end
