require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ParksController do

  # This should return the minimal set of attributes required to create a valid
  # Park. As you add validations to Park, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all parks as @parks" do
      park = Park.create! valid_attributes
      get :index
      assigns(:parks).should eq([park])
    end
  end

  describe "GET show" do
    it "assigns the requested park as @park" do
      park = Park.create! valid_attributes
      get :show, :id => park.id.to_s
      assigns(:park).should eq(park)
    end
  end

  describe "GET new" do
    it "assigns a new park as @park" do
      get :new
      assigns(:park).should be_a_new(Park)
    end
  end

  describe "GET edit" do
    it "assigns the requested park as @park" do
      park = Park.create! valid_attributes
      get :edit, :id => park.id.to_s
      assigns(:park).should eq(park)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Park" do
        expect {
          post :create, :park => valid_attributes
        }.to change(Park, :count).by(1)
      end

      it "assigns a newly created park as @park" do
        post :create, :park => valid_attributes
        assigns(:park).should be_a(Park)
        assigns(:park).should be_persisted
      end

      it "redirects to the created park" do
        post :create, :park => valid_attributes
        response.should redirect_to(Park.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved park as @park" do
        # Trigger the behavior that occurs when invalid params are submitted
        Park.any_instance.stub(:save).and_return(false)
        post :create, :park => {}
        assigns(:park).should be_a_new(Park)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Park.any_instance.stub(:save).and_return(false)
        post :create, :park => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested park" do
        park = Park.create! valid_attributes
        # Assuming there are no other parks in the database, this
        # specifies that the Park created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Park.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => park.id, :park => {'these' => 'params'}
      end

      it "assigns the requested park as @park" do
        park = Park.create! valid_attributes
        put :update, :id => park.id, :park => valid_attributes
        assigns(:park).should eq(park)
      end

      it "redirects to the park" do
        park = Park.create! valid_attributes
        put :update, :id => park.id, :park => valid_attributes
        response.should redirect_to(park)
      end
    end

    describe "with invalid params" do
      it "assigns the park as @park" do
        park = Park.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Park.any_instance.stub(:save).and_return(false)
        put :update, :id => park.id.to_s, :park => {}
        assigns(:park).should eq(park)
      end

      it "re-renders the 'edit' template" do
        park = Park.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Park.any_instance.stub(:save).and_return(false)
        put :update, :id => park.id.to_s, :park => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested park" do
      park = Park.create! valid_attributes
      expect {
        delete :destroy, :id => park.id.to_s
      }.to change(Park, :count).by(-1)
    end

    it "redirects to the parks list" do
      park = Park.create! valid_attributes
      delete :destroy, :id => park.id.to_s
      response.should redirect_to(parks_url)
    end
  end

end
